---
- name: 1. install Apache
  apt: name=apache2 state=present
  become: true

- name: 2. install list of PHP modules for Apache
  yum: name={{item}} state=present
  with_items:
    - php-common-7.2.16-1.amzn2.0.1
    - php-fpm-7.2.16-1.amzn2.0.1
    - php-json-7.2.16-1.amzn2.0.1
    - php-pdo-7.2.16-1.amzn2.0.1
    - php-pecl-imagick-3.4.3-3.amzn2.0.1
    - php-pecl-zip-1.15.2-3.amzn2.0.1
    - php-xml-7.2.16-1.amzn2.0.1
    - php-mbstring-7.2.16-1.amzn2.0.1
    - php-cli-7.2.16-1.amzn2.0.1
    - php-mysqlnd-7.2.16-1.amzn2.0.1
  become: true

- name: 3. Copy apache2 config
  copy:
    src: ../../configs/httpd.conf
    dest: /etc/httpd/conf/httpd.conf
    owner: root
    group: root
    mode: '0644'

- name: 4. remove default apache index 
  file: 
    path: /var/www/html/index.html
    state: absent
  become: true

- name: 5. install Hello World PHP script
  copy: src=index.php dest=/var/www/html/index.php mode=0664
  become: true

- name: 6. start Apache
  service: name=apache2 state=started enabled=yes
  become: true